### ISSUE TITLE
plugin configuration

### ISSUE THREAD

**Issue by letroll** [alvaromarco/CleanArchitecturePlugin#1]
I copy the files in the fileTemplates folder indicated in the description (.AndroidStudio2.1\config\fileTemplates), as well as in the folder (.AndroidStudio2.1\config\fileTemplates\code) but the plugin does not work

Plugin Error: Clean Architecture Generator threw an uncaught IncorrectOperationException. Disable Plugin
10:22:59 IncorrectOperationException
         This template did not produce a Java class or an interface

could you help me?

**Comment by alvaromarco** [comment]
You need copy the files exactly in .AndroidStudio2.1\config\fileTemplates. Not in folder \code
Like the image.
![example](https://cloud.githubusercontent.com/assets/18148336/18165872/13d2d364-7048-11e6-82c7-4a3673549143.png)
