### ISSUE TITLE
IncorrectOperationException 

### ISSUE THREAD

**Issue by Ternence** [alvaromarco/CleanArchitecturePlugin#4]
Hi , My studio caused this error when I generating Activity.   
```

IncorrectOperationException
          This template did not produce a Java class or an interface
          /*
          * Created by Android Studio.
          * User: ternence
          * Date: 2016/12/12
          * Time: 下午7:02
          */
          package test.a.opda.cn.myapplication.util;
          public utilscleanarch Constants { }

```
I  both added files in /Library/Preferences/AndroidStudio2.2/config/fileTemplates  and     .../.AndroidStudio2.2/config/fileTemplates.  Which path is right path ?  

thank you.

**Comment by alvaromarco** [comment]
The right path is where you installed your Android Studio 2.2, I don't know why you have 2 paths, I think is the same path so remove templates to relative path
