### ISSUE TITLE
How to import "template files" on Mac?

### ISSUE THREAD

**Issue by atreydos** [alvaromarco/CleanArchitecturePlugin#5]

**Comment by alvaromarco** [comment]
You need to find the  AndroidStudioConfig folder and copy the files in: /config/fileTemplates. If not created the folder 'fileTemplates' you need to created.

**Comment by Gilb007** [comment]
hello,

i couldn't find AndroidStudioConfig on mac.
so where to create "/config/fileTemplates"?

**Comment by finalight** [comment]
@alvaromarco can you provide a screenshot for android studio on mac instead? That way it's easier for us to follow as well
