### ISSUE TITLE
problem when use plugin on mac

### ISSUE THREAD

**Issue by Gilb007** [alvaromarco/CleanArchitecturePlugin#7]
Hello, please help me!

I use an android studio on Mac and didn't find where to put templates files.
There are not .AndroidStudioConfigVersion/config/fileTemplates, not even .AndroidStudioConfigVersion folder.

The same problem:

29.06.17
16:10	IncorrectOperationException
			This template did not produce a Java class or an interface
			/*
			* Created by Android Studio.
			* User: admin
			* Date: 29.06.17
			* Time: 16:10
			*/
			package com.ufc.OFK.util;
			public utilscleanarch Constants { }

**Comment by alvaromarco** [comment]
You need to search a folder like `.AndroidStudioConfig2.3` in your system. The folder by default is in `~/Library/Preferences/AndroidStudioConfig2.3`
